### ISSUE TITLE
Performance/ Design: How Maps will be stored in ram and on disk/

### ISSUE THREAD

**Issue by RichardlL** [PistonDevelopers/hematite_server#107]
### Right now, current options are

**1. Keep an array of block id/ data, as defined in the new 1.9 data format, 4096 indices per chunk section pointing to a position in the above array**
- Ram usage of 57 megabytes+ 2bytes per unique block including light data for a render distance of 10

**2. Keep just generate the indices when the client wants the chunk, and keep the block ID/data individually.**
- ram usage of 86.704128 megabytes for single player with light data, with render distance of 10

**3. *Structures based / 1.9 hybrid**

ram usage of 5 bytes for each block that is not the same as previous, +5 for light with the same restriction, + 2 bytes per unique block type/data
- minimum of 4.41 **kilobytes** for map that is completely flat (any hieght)
- maximum of 144.50688 megabytes for every block having no repeats

**4. Possible hybrid approach for high entropy situations**
- Maybe have a height cutoff for the previous aproach, as above the surface has much more entropy than below.
- Or just leave parts of the Structure layout blank. and if it is, check another array sequentially for the blank spaces
  - This would have a ram usage of 6 bytes for every 5+ more blocks
    or 2 byte for high entropy areas 
  - minimum of 10 **kilobytes** for completely flat map of any height, maximum of 57 megabytes for a extremely high amount of data, as per option 1

---

**\***
Rather than storing blocks, I was planning on storing "structures". These are very simple, but to have a hierarchy to assemble the map

The structure layout would be

```
Block Id / Data | starting position | ending position
----------------------------------------------
    2 bytes     |      u16          | u16
```

BlockID is the same as how its sent to the client (u16 = (id << 4 )| data)
Starting position is the yxz coordinate, non array (u16 = y \* 16 + x \* 16 + z \* 16)
and ending position is where that specific blocks would stop being repeated

Each chunk would have a vector of many of these structures

Each structure shadows all the ones before it. If you want to send blocks to the player, you find in the vector where the block is valid, then find where it might be shadowed, and the difference to the player's stream, so a one demensional cross section of a tree would be

```
  air | 0 | 16
-------------
leaves | 5 | 14
-------------
wood | 9 | 10
```

and the algorithm process would look like

```
let current_position = 0;
let mut length = 0;
while current_position < end_of chunk {
    for z in (structure backwords) {
        if current position is in (z startingposition - i.ending position){
            for a in structure.last..structure.z  { 
                // If a new structure overshadows part of this one
                if a.starting_posisition is < z.endingposition {
                    length = a.starting - z.starting position
                    current_position += length;
                    break; (to outside of first for (inside while))
                }
             }
            // otherwise we use the whole structure
             length = z.end_position - z.starting_position;
             current_position += length
        }
      }
    *
      for 0..length {
          stream.write(z.data) 
      }
}
```

*We wouldnt actually use a loop here, see https://en.wikipedia.org/wiki/DEFLATE#Duplicate_string_elimination

Which would end up making the tree cross section look like this

```
----####X####--
where 
- air
# leaves
X woood
```

**Comment by RichardlL** [comment]
@fenhl @toqueteos

**Comment by toqueteos** [comment]
_Sorry for the delay!_ :tada: 

I can't talk much about first part without digging into the numbers you gave but it seems like **option 1** is the best candidate and the easier to do once 1.9 lands. Right now we are still on 1.8.8 (I'll send a PR to update to 1.8.9 ASAP) so there's plain old chunk format. The new block palettes offer a promising improvement, we'll see how it turns out.

About the second part, it seems you are proposing something like XY axis quadtrees instead of regular XZ axis chunk sections but with builtin awareness of different _"structures"_. This seems interesting but I don't really know if the naive implementation works bad enough in order for your proposal to be worth it. Don't forget that we must have all blocks in memory so we can perform updates; being a multiplayer server multiple updates can happen at the same time so we also need synchronization. With this proposal any possible speed/memory improvements add a runtime cost for compression you need to account for that too which can be quite intense with a big number of players on the server. CPU time is a precious resource, especially in the future when we start adding support for entities, we need to optimize for it. Memory isn't a problem right now but it'll probably be in the future.

I would focus on getting something naive but compatible with current Minecraft and then after that dig down into specific performance improvements.

**Comment by fenhl** [comment]
+1 to everything @toqueteos said, plus using the same format in memory as over the network can save encode/decode time and allow for huge memory improvements in singleplayer if and when singleplayer protocol (#97) is implemented, since server and client would use the same memory.

**Comment by RichardlL** [comment]
Makes sense!

**Comment by toqueteos** [comment]
@RichardlL No need to close this buddy, you can just leave it for future discussions.

**Comment by fenhl** [comment]
If any further discussion happens later, we can reopen the issue then. We should have a tracking issue for migrating to the 1.9 chunk format though.
