### ISSUE TITLE
Rename project to hematite-server

### ISSUE THREAD

**Issue by fenhl** [PistonDevelopers/hematite_server#68]
The same name except with a hyphen instead of an underscore.

Pros:
-   Seems to be the more common style for binaries
-   Easy to work with because of recent changes in crate name semantics

Cons:
-   Inconsistent with Notchian `minecraft_server.jar`

**Comment by toqueteos** [comment]
I like the way it is, I would rename it to `hematite_core` though because most of it is shared for both client and server.
- `extern crate hematite_server` works.
- `extern crate hematite-server` doesn't work, we are forced to `extern crate "hematite-server" as hem`.

If it's all about the binary, just rename the binary name in `Cargo.toml`.

**Comment by fenhl** [comment]
Looks like you missed the recent changes in crate name semantics. The crate can be named `hematite-server` and `extern crate hematite_server` will still work. The syntax with the quotes no longer exists (or will go away very soon).

**Comment by toqueteos** [comment]
What I'm saying is that we should stick with just one name for everything, it's the best approach in the long term.

**Comment by fenhl** [comment]
It would still be one name for everything.

**Comment by toqueteos** [comment]
:+1: for `hematite_server`

**Comment by fenhl** [comment]
Closing since no one seems to be in favor.
